from django.urls import path

from . import views
from . import search_views

urlpatterns = [
    path('api/user/<str:user_name>/', views.get_user_info),
    path('api/user/', views.user_register),
    path('api/user-tag/', views.post_user_tag),
    path('api/email/send/', views.user_send_validate_email),
    path('api/email/validate/', views.user_email_code_validate),
    path('api/reset-psw-email/send/', views.send_reset_password_email),
    path('api/reset-psw-email/validate/', views.validate_reset_password_email),
    path('api/alter-user-info/', views.alter_user_info),
    path('api/login/', views.login),
    path('api/login/resume/', views.resume_login),
    path('api/questions/<int:page>/', views.get_questions_by_pages),
    path('api/questions/', views.post_question),
    path('api/questions/detail/<int:question_id>/', views.get_question_by_id),
    path('api/questions/delete/', views.delete_question),
    path('api/questions/hottest/', views.get_hottest_questions),
    path('api/questions/suggested/', views.get_suggested_questions),
    path('api/questions/user/<str:user_name>/<int:page>/', views.get_user_questions),
    path('api/questions/topic/<str:topic>/', views.get_question_by_topic),
    path('api/questions/topic/', views.get_question_all_topics),
    path('api/answers/', views.post_answer),
    path('api/answers/vote/', views.post_answer_vote),
    path('api/answers/question/<int:question_id>/', views.get_question_answers),
    path('api/answers/question/user/<str:user_name>/', views.get_user_answers),
    path('api/answers/delete/', views.delete_answer),
    path('api/comments/', views.post_comment),
    path('api/comments/vote/', views.post_comment_vote),
    path('api/comments/answer/<int:answer_id>/<int:page>/', views.get_answer_comments),
    path('api/comments/<int:comment_id>/<int:page>/', views.get_all_reply_comments),
    path('api/comments/user/<str:user_name>/<int:page>/', views.get_user_comments),
    path('api/messages/', views.get_lattest_messages),
    path('api/messages/<int:page>/', views.get_message_by_page),
    path('api/messages/question/<int:question_id>/', views.get_message_by_question_id),
    path('api/handbook/', views.post_create_handbook),
    path('api/handbook/alter/', views.post_alter_handbook),
    path('api/handbook/category-order/<str:category>/<int:order>/', views.get_handbook_by_category_and_order),
    path('api/handbook/raw/<str:category>/<int:order>/', views.get_handbook_raw_by_category_and_order),
    path('api/handbook/brief/<str:category>/<int:order>/', views.get_brief_handbook_by_category_and_order),
    path('api/handbook/categories/', views.get_handbook_all_categories),
    path('api/handbook/category/<str:category>/', views.get_handbooks_by_category),
    path('api/handbook/user/<str:user_name>/', views.get_user_handbooks),
    path('api/handbook/modify/', views.post_handbook_modify),
    path('api/handbook/delete/', views.post_handbook_delete),
    path('api/handbook/next/<str:category>/<int:order>/', views.get_next_handbook),
    path('api/handbook/prev/<str:category>/<int:order>/', views.get_prev_handbook),
    path('api/drafts/<str:user_name>/<int:handbook_id>/', views.get_draft),
    path('api/drafts/modify/', views.post_draft_modify),
    path('api/drafts/publish/', views.post_publish_draft),
    path('api/drafts/delete/', views.post_draft_delete),
    path('api/search/', search_views.MySearchView(), name='haystack_search'),  # 全局搜索
    path('api/search/<str:model>/<str:query>/', views.search),  # 分类搜索
    path('api/get_cos_credential/', views.get_cos_credential),
    path('api/chat/', views.post_create_chat),
    path('api/chat/<str:user_name>/', views.get_chat),
    path('api/chat-message/<int:chat_id>/', views.get_chat_message),
    path('api/chat-message/', views.post_chat_message),
    path('api/chat-message/delete/', views.delete_chat_message),
    path('api/friendship/follow/', views.post_follow),
    path('api/friendship/unfollow/', views.post_unfollow),
    path('api/friendship/follower/<str:user_name>/', views.get_follower),
    path('api/friendship/follow/<str:user_name>/', views.get_follow),
    path('api/pair-post/', views.post_pair_degree),
    path('api/pair-initial/<str:user_name>/', views.get_initialize_pair),
    path('api/pair/<str:user_name>/', views.get_pair_degree),
    path('api/moment/', views.post_moment),
    path('api/moment/user/<str:user_name>/<int:page>/', views.get_user_moments),
    path('api/moment/lattest/<int:page>/', views.get_lattest_moments)
]
